-- Create tablespace for data
CREATE TABLESPACE DATA_TALLER
DATAFILE '/u01/data/PRD900/data_taller_01.dbf' SIZE 500m
AUTOEXTEND ON
SEGMENT SPACE MANAGEMENT AUTO;

-- Create tablespace for indexes
CREATE TABLESPACE INDEX_TALLER
DATAFILE '/u01/data/PRD900/index_taller_01.dbf' SIZE 500m
AUTOEXTEND ON
SEGMENT SPACE MANAGEMENT AUTO;

/* Para omitir la opcion de contenedores de la DB */

--alter session set _ORACLE_SCRIPT=true;

-- Create user for manage the database
CREATE USER COVID_TALLER
IDENTIFIED BY covid
DEFAULT TABLESPACE DATA_TALLER
TEMPORARY TABLESPACE temp
QUOTA 10M ON DATA_TALLER;

-- Give unlimited space in the tablespace
ALTER USER COVID_TALLER
QUOTA UNLIMITED ON DATA_TALLER;


-- Give privileges to user covid_taller
GRANT create session TO covid_taller;
GRANT create table TO covid_taller;
GRANT create view TO covid_taller;
GRANT create synonym TO covid_taller;
GRANT create procedure TO covid_taller;
GRANT create sequence TO covid_taller;
GRANT create trigger TO covid_taller;


-- Create tables
CREATE TABLE REGIONS(
    id VARCHAR2(5),
    name VARCHAR2(21)
);

CREATE TABLE COUNTRIES(
    code VARCHAR2(5),
    name VARCHAR2(70),
    id_region VARCHAR2(5)
);

CREATE TABLE CASES(
    id NUMBER(10),
    date_reported DATE,
    new_cases NUMBER(10),
    cumulative_cases NUMBER(10),
    new_deaths NUMBER(10),
    cumulative_deaths NUMBER(10),
    id_country VARCHAR2(5)
);

-- Temporary table for load of the data from the .csv
CREATE TABLE TEMP(
    date_reported DATE,
    country_code VARCHAR2(5),
    country VARCHAR2(70),
    region VARCHAR2(5),
    new_cases NUMBER(10),
    cumulative_cases NUMBER(10),
    new_deaths NUMBER(10),
    cumulative_deaths NUMBER(10)
);

-- Create sequence for the autoincrement property of the primary keys
CREATE SEQUENCE covid_sequence
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Create trigger for the autoincrement for each table
create or replace TRIGGER auto_increment_trigger_cases
BEFORE INSERT ON CASES
FOR EACH ROW
BEGIN
    :NEW.id := covid_sequence.NEXTVAL;
END;
/

-- Another method
/*
CREATE TABLE mi_tabla (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)
);
*/

-- Load the data into the tables wiht SQLDeveloper or SQLLOADER

-- Inserts from temp to the tables
INSERT INTO REGIONS(NAME) SELECT DISTINCT REGION FROM TEMP;

INSERT INTO COUNTRIES(CODE, NAME) select distinct country_code, country from temp;

insert into cases(date_reported, new_cases, cumulative_cases, new_deaths, cumulative_deaths, id_country) 
select date_reported, new_cases, cumulative_cases, new_deaths, cumulative_deaths, country_code from temp;

-- Add constraints
-- Primary keys
ALTER TABLE REGIONS ADD CONSTRAINT regions_pk PRIMARY KEY (id);
ALTER TABLE COUNTRIES ADD CONSTRAINT countries_pk PRIMARY KEY (code);
ALTER TABLE CASES ADD CONSTRAINT cases_pk PRIMARY KEY (id);

-- Foreing Keys
ALTER TABLE COUNTRIES ADD CONSTRAINT regions_fk_countries FOREIGN KEY (id_region)
REFERENCES regions (id);

ALTER TABLE CASES ADD CONSTRAINT countries_fk_cases FOREIGN KEY (id_country)
REFERENCES countries (code);